web:
  build: .
  ports:
    - "3000:3000"
  links:
    - mongo:mongo
    - redis:redis
  env_file: .env
  command: node /code/app.js

redis:
  image: redis:latest
  ports:
    - "6379:6379"

mongo:
  image: mongo:latest
  ports:
    - "27017:27017"
